### ISSUE TITLE
No support for flavor dimensions

### ISSUE THREAD

**Issue by SmilyOrg** [dannyjiajia/gradle-java-preprocessor-plugin#1]
When combining flavors using dimensions, each build variant can contain multiple flavors. When the processor plugin creates the tasks in `PreprocessorPlugin.groovy`, the `configProject` method tries to create a task for every flavor multiple times, which leads to a Gradle error. Only one flavor name and the build type are used for the task name, which has to be unique.

Am I missing something or does this not support flavor dimensions?

**Comment by dannyjiajia** [comment]
@SmilyOrg This not support flavor dimensions now,i will fix it ASAP

**Comment by dannyjiajia** [comment]
supported in 0.0.6

**Comment by SmilyOrg** [comment]
Thanks!
