### ISSUE TITLE
Combine buildTypes and Flavours

### ISSUE THREAD

**Issue by ardakaplan** [dannyjiajia/gradle-java-preprocessor-plugin#4]
Hi, 

is that possible to combine all types of flavorDimensions and buildTypes. 

For example; 

default buildTypes 
```
 buildTypes {
        release {
        }

        debug {
        }
    }
```
and custom flavorDimensions

```
flavorDimensions "environment", "company"
    productFlavors {

        pilot {
            processor.symbols "PILOT"
            dimension "environment"
        }

        internal {
            processor.symbols "INTERNAL"
            dimension "environment"
        }

        prod {
            processor.symbols "PROD"
            dimension "environment"
        }

  
        DD{
            processor.symbols "DD"
            dimension "company"
        }

        MM{
            processor.symbols "MM"
            dimension "company"
        }
    }
```

no i want to work with  "prodMMDebug" - "pilotMMDebug" - "prodMMRelease" ...etc.

how can i do that ?

**Comment by dannyjiajia** [comment]
hi @ardakaplan sorry for late reply, the symbols was combined. Just like the sample project:

![image](https://user-images.githubusercontent.com/2572540/60242846-59a07280-98e9-11e9-9248-8ce8fa4596c0.png)
